#
# Copyright (C) 2026 NonameBlank007
#
# SPDX-License-Identifier: GPL-3.0-only
#

from ..module import (
    baka,
    bite,
    bleh,
    blush,
    bonk,
    catpx,
    clap,
    confused,
    cuddle,
    dogpx,
    facts,
    feed,
    help,
    highfive,
    hug,
    jokes,
    kick,
    kiss,
    laugh,
    lurk,
    magisk,
    msg,
    nod,
    nom,
    nope,
    nya,
    pat,
    peck,
    plantpx,
    poke,
    punch,
    quotes,
    shoot,
    shrug,
    slap,
    sleep,
    smile,
    smug,
    stare,
    start,
    think,
    thumbsup,
    tickle,
    wave,
    wink,
    yeet,
)


class Handlers:
    MODULES = [
        start.StartModule,
        magisk.MagiskModule,
        facts.FactModule,
        baka.BakaModule,
        bonk.BonkModule,
        bite.BiteModule,
        bleh.BlehModule,
        blush.BlushModule,
        clap.ClapModule,
        confused.ConfModule,
        cuddle.CuddleModule,
        feed.FeedModule,
        highfive.HFModule,
        hug.HugModule,
        kick.KickModule,
        kiss.KissModule,
        laugh.LaughModule,
        nod.NodModule,
        nom.NomModule,
        nope.NopeModule,
        nya.NyaModule,
        pat.PatModule,
        peck.PeckModule,
        poke.PokeModule,
        punch.PunchModule,
        shoot.ShootModule,
        shrug.ShrugModule,
        slap.SlapModule,
        sleep.SleepModule,
        smile.SmileModule,
        smug.SmugModule,
        stare.StareModule,
        think.ThinkModule,
        thumbsup.TUModule,
        tickle.TickleModule,
        wave.WaveModule,
        wink.WinkModule,
        yeet.YeetModule,
        jokes.JokeModule,
        msg.MsgModule,
        lurk.LurkModule,
        catpx.CatpxModule,
        quotes.QuoteModule,
        help.HelpModule,
        dogpx.DogpxModule,
        plantpx.PlaModule,
    ]

    @classmethod
    def register(cls, app):
        for module in cls.MODULES:
            module.setup(app)
